### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by FluffleDUF** [matthe815/matthews-difficulty-mod#40]
This ain’t a bug, it’s more a confusion on my part, is there anyway to make the HUD of the Hunger/Thirst the one displayed in these images?

![BE686B29-0CC2-4389-A807-C7AF25E64DF7](https://user-images.githubusercontent.com/112727046/188223628-7983ed4e-c73b-4312-a871-e6114e05b11e.png)
![7038CA18-8965-40C2-AC90-EC0615439D8D](https://user-images.githubusercontent.com/112727046/188223632-995c219e-49f8-44be-81c7-ea43b4be4ad0.png)

I don’t know if is a way or not but it would be most appreciated if you can provide an answer

**Comment by matthe815** [comment]
The "Use TAN UI" in the config should be enabled
